import type { Request, Response, NextFunction } from "express";

/**
 * Requires every voter-initiated request to carry an `x-voter-id` header.
 *
 * The voter id is generated by the client (UUID stored in localStorage) and
 * is the primitive that lets the API tell distinct voters apart for things
 * like "change my vote" (POL-7) and option authorship (POL-10) without
 * introducing a real auth system. The id is opaque and self-asserted; trust
 * model matches the existing client-side `polopine:voted:` markers.
 *
 * Attaches the trimmed id to `res.locals.voterId` for handlers downstream.
 */
export function requireVoterId(
  req: Request,
  res: Response,
  next: NextFunction,
): void {
  const raw = req.header("x-voter-id");
  if (typeof raw !== "string" || raw.trim().length === 0) {
    res.status(400).json({ error: "x-voter-id header required" });
    return;
  }

  const voterId = raw.trim();
  if (voterId.length > 128) {
    res.status(400).json({ error: "x-voter-id header too long" });
    return;
  }

  res.locals.voterId = voterId;
  next();
}
